apiVersion: apps/v1
kind: Deployment
metadata:
    name: rca-org1
    labels:
        app: rca-org1-root
spec:
    selector:
        matchLabels:
            app: rca-org1-root
    template:
        metadata: 
            labels:
                app: rca-org1-root
        spec:
            containers:
              - name: rca-org1
                image: hyperledger/fabric-ca
                command: ["fabric-ca-server", "start", "-b", "rca-org1-admin:rca-org1-adminpw", "--port", "7054"]
                env:
                - name: FABRIC_CA_HOME
                  value: "/etc/hyperledger/fabric-ca-server"
                - name: FABRIC_CA_SERVER_TLS_ENABLED
                  value: "true"
                - name: FABRIC_CA_SERVER_CSR_CN
                  value: "rca-org1"
                - name: FABRIC_CA_SERVER_CSR_HOSTS
                  value: "${IP}"
                - name: FABRIC_CA_SERVER_DEBUG
                  value: "true"
