apiVersion: v1
kind: Service
metadata:
  name: rca-org1
  labels:
    app: rca-org1-root
spec:
  type: NodePort
  selector:
    app: rca-org1-root
  ports:
    - protocol: TCP
      nodePort: 30907
      targetPort: 7054
      port: 7054