apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  namespace: hlf
  labels:
    app: dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
        - name: docker
          securityContext:
            privileged: true
          image: "docker:18.05.0-dind"
          ports:
            - containerPort: 2375
---
apiVersion: v1
kind: Service
metadata:
  name: dind
  namespace: hlf
  labels:
    app: dind
spec:
  selector:
    app: dind
  ports:
    - name: docker-host
      protocol: TCP
      targetPort: 2375
      port: 2375