apiVersion: v1
kind: Service
metadata:
  name: rca-org2
  labels:
    app: rca-org2-root
spec:
  type: NodePort
  selector:
    app: rca-org2-root
  ports:
    - protocol: TCP
      nodePort: 30908
      targetPort: 7055
      port: 7055