apiVersion: apps/v1
kind: Deployment
metadata:
  name: rca-org1
  namespace: hlf
  labels:
    app: rca-org1
spec:
  selector:
    matchLabels:
      app: rca-org1
  template:
    metadata:
      labels:
        app: rca-org1
    spec:
      containers:
        - name: rca-org1
          image: hyperledger/fabric-ca:1.4.7
          imagePullPolicy: IfNotPresent
          command: ["fabric-ca-server", "start", "-b", "$(BOOTSTRAP_USER):$(BOOTSTRAP_PASSWORD)", "--port", "7054"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/secrets/cert.pem
              name: cert
              subPath: cert.pem
              readOnly: true
            - mountPath: /tmp/secrets/key.pem
              name: key
              subPath: key.pem
              readOnly: true
          env:
            - name: FABRIC_CA_HOME
              value: "/tmp/hyperledger/fabric-ca/crypto"
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_CSR_CN
              value: "rca-org1"
            - name: FABRIC_CA_SERVER_CSR_HOSTS
              value: "172.17.0.2,172.17.0.3,0.0.0.0,rca-org1.hlf"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: "/tmp/secrets/cert.pem"
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: "/tmp/secrets/key.pem"
            - name: BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.rca-org1
                  key: username
            - name: BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.rca-org1
                  key: password
            - name: PEER1_ORG1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.peer1-org1
                  key: username
            - name: PEER1_ORG1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.peer1-org1
                  key: password
            - name: PEER2_ORG1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.peer2-org1
                  key: username
            - name: PEER2_ORG1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.peer2-org1
                  key: password
            - name: ADMIN_ORG1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-org1
                  key: username
            - name: ADMIN_ORG1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-org1
                  key: password
            - name: SCALA_ADMIN_ORG1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-admin-org1
                  key: username
            - name: SCALA_ADMIN_ORG1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-admin-org1
                  key: password
            - name: SCALA_REGISTRATION_ADMIN_ORG1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-registration-admin-org1
                  key: username
            - name: SCALA_REGISTRATION_ADMIN_ORG1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-registration-admin-org1
                  key: password
      volumes:
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: cert
          secret:
            secretName: cert.rca-org1
        - name: key
          secret:
            secretName: key.rca-org1
---
apiVersion: v1
kind: Service
metadata:
  name: rca-org1
  namespace: hlf
  labels:
    app: rca-org1
spec:
  type: NodePort
  selector:
    app: rca-org1
  ports:
    - name: https
      protocol: TCP
      nodePort: 30907
      targetPort: 7054
      port: 7054
