apiVersion: v1
kind: Service
metadata:
  name: rca-org0
  labels:
    app: rca-org0-root
spec:
  type: NodePort
  selector:
    app: rca-org0-root
  ports:
    - protocol: TCP
      nodePort: 30906
      targetPort: 7053
      port: 7053