apiVersion: apps/v1
kind: Deployment
metadata:
  name: rca-org0
  namespace: hlf
  labels:
    app: rca-org0
spec:
  selector:
    matchLabels:
      app: rca-org0
  template:
    metadata:
      labels:
        app: rca-org0
    spec:
      containers:
        - name: rca-org0
          image: hyperledger/fabric-ca:1.4.7
          imagePullPolicy: IfNotPresent
          command: ["fabric-ca-server", "start", "-b", "$(BOOTSTRAP_USER):$(BOOTSTRAP_PASSWORD)", "--port", "7053"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/cert.pem
              name: cert
              subPath: cert.pem
              readOnly: true
            - mountPath: /tmp/secrets/key.pem
              name: key
              subPath: key.pem
              readOnly: true
          env:
            - name: FABRIC_CA_HOME
              value: "/tmp/hyperledger/fabric-ca/crypto"
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_CSR_CN
              value: "rca-org0"
            - name: FABRIC_CA_SERVER_CSR_HOSTS
              value: "172.17.0.2,172.17.0.3,0.0.0.0,rca-org0.hlf"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: "/tmp/secrets/cert.pem"
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: "/tmp/secrets/key.pem"
            - name: BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.rca-org0
                  key: username
            - name: BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.rca-org0
                  key: password
            - name: ORDERER_ORG0_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.orderer-org0
                  key: username
            - name: ORDERER_ORG0_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.orderer-org0
                  key: password
            - name: ADMIN_ORG0_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-org0
                  key: username
            - name: ADMIN_ORG0_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-org0
                  key: password
      volumes:
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: tls-ca-cert
          secret:
            secretName: cert.tls-ca
        - name: cert
          secret:
            secretName: cert.rca-org0
        - name: key
          secret:
            secretName: key.rca-org0

---
apiVersion: v1
kind: Service
metadata:
  name: rca-org0
  namespace: hlf
  labels:
    app: rca-org0
spec:
  type: NodePort
  selector:
    app: rca-org0
  ports:
    - name: https
      protocol: TCP
      nodePort: 30906
      targetPort: 7053
      port: 7053
