apiVersion: v1
kind: Service
metadata:
  name: ca-tls
  labels:
    app: ca-tls-root
spec:
  type: NodePort
  selector:
    app: ca-tls-root
  ports:
    - protocol: TCP
      nodePort: 30905
      targetPort: 7052
      port: 7052