apiVersion: v1
kind: PersistentVolume
metadata:
  name: tls-ca-pv
  labels:
    type: local
    name: tls-ca-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain